# Generated by Django 3.1 on 2020-08-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_event_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, default='noneImage.jpg', null=True, upload_to=''),
        ),
    ]
